In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN","NAME"])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ["T9","T13","T12","T2","T14","T25","T15","T29","T17"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts_1 = classification_counts[classification_counts > 1]
print(classification_counts_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 1883
classifications_to_replace = classification_counts[classification_counts < cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=["APPLICATION_TYPE", "CLASSIFICATION", "AFFILIATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT", "SPECIAL_CONSIDERATIONS", "STATUS"])

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=["IS_SUCCESSFUL"])
y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=X_train_scaled.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │           3,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,061 (23.68 KB)

 Trainable params: 6,061 (23.68 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
# Compile the model
nn.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [14]:
# Train the model
history = nn.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6396 - loss: 2.1659 - val_accuracy: 0.6990 - val_loss: 0.7848
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7071 - loss: 0.8280 - val_accuracy: 0.7125 - val_loss: 0.8750
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7045 - loss: 0.8309 - val_accuracy: 0.6992 - val_loss: 1.2431
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6931 - loss: 1.2483 - val_accuracy: 0.7025 - val_loss: 1.1395
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6982 - loss: 1.1284 - val_accuracy: 0.7209 - val_loss: 0.6811
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7025 - loss: 0.8480 - val_accuracy: 0.7283 - val_loss: 0.6663
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7245 - loss: 0.6521 - val_accuracy: 0.7185 - val_loss: 0.7074
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7211 - loss: 0.6587 - val_accuracy: 0.7245 - val_loss: 0.6231
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7317 - loss: 0.6026 - val_accuracy: 0.7258 - val_loss: 0.6005
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7257 - loss: 0.6798 - val_accuracy: 0.7194 - val_loss: 0.7664
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7303 - loss: 0.7149 - val_accuracy: 0.7141 - val_loss: 0.7192
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7254 - loss: 0.7159 - val_accuracy: 0.7220 - val_loss: 0.7306
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7278 - loss: 0.6246 - val_accuracy: 0.7294 - val_loss: 0.6225
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7303 - loss: 0.6128 - val_accuracy: 0.7170 - val_loss: 0.6440
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7288 - loss: 0.6402 - val_accuracy: 0.7286 - val_loss: 0.6281
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7244 - loss: 0.6156 - val_accuracy: 0.7304 - val_loss: 0.6179
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7293 - loss: 0.6041 - val_accuracy: 0.7305 - val_loss: 0.5939
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7350 - loss: 0.5996 - val_accuracy: 0.7244 - val_loss: 0.6110
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7295 - loss: 0.5887 - val_accuracy: 0.7276 - val_loss: 0.6100
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7324 - loss: 0.6149 - val_accuracy: 0.7243 - val_loss: 0.6512
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7279 - loss: 0.6337 - val_accuracy: 0.7259 - val_loss: 0.6082
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7297 - loss: 0.5910 - val_accuracy: 0.7261 - val_loss: 0.5919
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7297 - loss: 0.5841 - val_accuracy: 0.7303 - val_loss: 0.5918
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7301 - loss: 0.5920 - val_accuracy: 0.7242 - val_loss: 0.5915
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7334 - loss: 0.5913 - val_accuracy: 0.7294 - val_loss: 0.6077
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7270 - loss: 0.6063 - val_accuracy: 0.7157 - val_loss: 0.5954
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7275 - loss: 0.5837 - val_accuracy: 0.7283 - val_loss: 0.5995
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7377 - loss: 0.5845 - val_accuracy: 0.7301 - val_loss: 0.5893
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7284 - loss: 0.6250 - val_accuracy: 0.7285 - val_loss: 0.5903
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7305 - loss: 0.5916 - val_accuracy: 0.7299 - val_loss: 0.5942
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7325 - loss: 0.5744 - val_accuracy: 0.7173 - val_loss: 0.5997
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7276 - loss: 0.5986 - val_accuracy: 0.7280 - val_loss: 0.5874
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7392 - loss: 0.5832 - val_accuracy: 0.7279 - val_loss: 0.5926
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7335 - loss: 0.5808 - val_accuracy: 0.7287 - val_loss: 0.5905
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7330 - loss: 0.5907 - val_accuracy: 0.7285 - val_loss: 0.5833
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7363 - loss: 0.5916 - val_accuracy: 0.7294 - val_loss: 0.5896
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7318 - loss: 0.5851 - val_accuracy: 0.7179 - val_loss: 0.5904
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7358 - loss: 0.5778 - val_accuracy: 0.7293 - val_loss: 0.5943
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7375 - loss: 0.5803 - val_accuracy: 0.7315 - val_loss: 0.5865
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7364 - loss: 0.5832 - val_accuracy: 0.7301 - val_loss: 0.5793
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7314 - loss: 0.5773 - val_accuracy: 0.7264 - val_loss: 0.5887
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7299 - loss: 0.5735 - val_accuracy: 0.7293 - val_loss: 0.5814
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7386 - loss: 0.5722 - val_accuracy: 0.7227 - val_loss: 0.5808
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7298 - loss: 0.5828 - val_accuracy: 0.7299 - val_loss: 0.6128
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7365 - loss: 0.5742 - val_accuracy: 0.7285 - val_loss: 0.6030
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7349 - loss: 0.5860 - val_accuracy: 0.7287 - val_loss: 0.6025
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7383 - loss: 0.5827 - val_accuracy: 0.7265 - val_loss: 0.5918
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7342 - loss: 0.5740 - val_accuracy: 0.7285 - val_loss: 0.5991
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7373 - loss: 0.5637 - val_accuracy: 0.7287 - val_loss: 0.6366
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7377 - loss: 0.5799 - val_accuracy: 0.7290 - val_loss: 0.5879
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7374 - loss: 0.5707 - val_accuracy: 0.7289 - val_loss: 0.6044
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7399 - loss: 0.5740 - val_accuracy: 0.7287 - val_loss: 0.6305
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7373 - loss: 0.5817 - val_accuracy: 0.7289 - val_loss: 0.6014
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7328 - loss: 0.5756 - val_accuracy: 0.7265 - val_loss: 0.6056
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7396 - loss: 0.5745 - val_accuracy: 0.7292 - val_loss: 0.6137
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7420 - loss: 0.5829 - val_accuracy: 0.7243 - val_loss: 0.6132
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7335 - loss: 0.5780 - val_accuracy: 0.7283 - val_loss: 0.6121
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7357 - loss: 0.5678 - val_accuracy: 0.7264 - val_loss: 0.6018
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7418 - loss: 0.5703 - val_accuracy: 0.7278 - val_loss: 0.6097
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7280 - loss: 0.5816 - val_accuracy: 0.7272 - val_loss: 0.6098
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7321 - loss: 0.5810 - val_accuracy: 0.7291 - val_loss: 0.6102
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7371 - loss: 0.5766 - val_accuracy: 0.7266 - val_loss: 0.6084
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7367 - loss: 0.6128 - val_accuracy: 0.7250 - val_loss: 0.6165
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7322 - loss: 0.5771 - val_accuracy: 0.7284 - val_loss: 0.5904
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7292 - loss: 0.5751 - val_accuracy: 0.7283 - val_loss: 0.5991
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7369 - loss: 0.5772 - val_accuracy: 0.7296 - val_loss: 0.5913
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7389 - loss: 0.5606 - val_accuracy: 0.7238 - val_loss: 0.5913
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7415 - loss: 0.5579 - val_accuracy: 0.7283 - val_loss: 0.6067
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7412 - loss: 0.5743 - val_accuracy: 0.7298 - val_loss: 0.6040
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7273 - loss: 0.5813 - val_accuracy: 0.7268 - val_loss: 0.5878
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7388 - loss: 0.5631 - val_accuracy: 0.7297 - val_loss: 0.5816
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7355 - loss: 0.5713 - val_accuracy: 0.7286 - val_loss: 0.5977
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7324 - loss: 0.5749 - val_accuracy: 0.7241 - val_loss: 0.6159
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7261 - loss: 0.5875 - val_accuracy: 0.7291 - val_loss: 0.6140
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7336 - loss: 0.5884 - val_accuracy: 0.7276 - val_loss: 0.6088
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7334 - loss: 0.5785 - val_accuracy: 0.7291 - val_loss: 0.6045
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7428 - loss: 0.5704 - val_accuracy: 0.7279 - val_loss: 0.6095
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7384 - loss: 0.5763 - val_accuracy: 0.7285 - val_loss: 0.6009
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7348 - loss: 0.5686 - val_accuracy: 0.7286 - val_loss: 0.6070
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7281 - loss: 0.5791 - val_accuracy: 0.7283 - val_loss: 0.5980
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7358 - loss: 0.5645 - val_accuracy: 0.7294 - val_loss: 0.5920
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7289 - loss: 0.5827 - val_accuracy: 0.7318 - val_loss: 0.5926
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7375 - loss: 0.5608 - val_accuracy: 0.7289 - val_loss: 0.5884
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7350 - loss: 0.5642 - val_accuracy: 0.7279 - val_loss: 0.5871
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7403 - loss: 0.5712 - val_accuracy: 0.7265 - val_loss: 0.6108
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7187 - loss: 0.5912 - val_accuracy: 0.7283 - val_loss: 0.6061
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7385 - loss: 0.5704 - val_accuracy: 0.7275 - val_loss: 0.5945
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7364 - loss: 0.5714 - val_accuracy: 0.7176 - val_loss: 0.6158
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7275 - loss: 0.5856 - val_accuracy: 0.7255 - val_loss: 0.6196
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7374 - loss: 0.5943 - val_accuracy: 0.7286 - val_loss: 0.6376
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7412 - loss: 0.5948 - val_accuracy: 0.7277 - val_loss: 0.6346
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7371 - loss: 0.6068 - val_accuracy: 0.7277 - val_loss: 0.6388
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7397 - loss: 0.6079 - val_accuracy: 0.7278 - val_loss: 0.6481
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7365 - loss: 0.5963 - val_accuracy: 0.7195 - val_loss: 0.6197
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7291 - loss: 0.5982 - val_accuracy: 0.7290 - val_loss: 0.6685
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7415 - loss: 0.6102 - val_accuracy: 0.7294 - val_loss: 0.6467
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7339 - loss: 0.6254 - val_accuracy: 0.7289 - val_loss: 0.6417
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7352 - loss: 0.6477 - val_accuracy: 0.7283 - val_loss: 0.7352
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7299 - loss: 0.7010 - val_accuracy: 0.7266 - val_loss: 0.6502
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7391 - loss: 0.6061 - val_accuracy: 0.7290 - val_loss: 0.6507

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Model Accuracy: {model_accuracy * 100:.2f}%")

268/268 - 1s - 3ms/step - accuracy: 0.7290 - loss: 0.6507
Model Accuracy: 72.90%

In [16]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.